import { Injectable } from '@nestjs/common';

import { TravelDirection, VehicleClass } from '@smartpark/contracts';
import { GenericWebhookAnprProvider } from './generic-webhook.provider';
import { AnprProvider, NormalizedAnprEvent } from '../anpr.provider';

/**
 * Development ANPR adapter.
 *
 * Accepts the same payload shape as the production webhook adapter - it simply
 * subclasses it - so a developer exercises the real parsing path. What it adds
 * is `simulate()`, which manufactures a capture for a given plate so the gate
 * workflow can be driven from the console or from a test without any camera
 * hardware.
 *
 * It relaxes exactly one thing: signature verification always passes, because
 * there is no camera to hold a shared secret. Everything else - de-duplication,
 * the confidence threshold, the review queue, idempotency - behaves identically
 * to production. Configuration refuses to boot production with this provider.
 */
@Injectable()
export class MockAnprProvider extends AnprProvider {
  readonly name = 'mock';

  private readonly delegate = new GenericWebhookAnprProvider();
  private sequence = 0;

  normalize(payload: unknown): NormalizedAnprEvent {
    return this.delegate.normalize(payload);
  }

  /** Always valid: there is no hardware to sign with. */
  verifySignature(): { valid: boolean; reason?: string } {
    return { valid: true };
  }

  /**
   * Manufactures a capture event.
   *
   * `confidence` defaults just above a typical threshold. Passing a low value
   * is how the manual-review path is exercised in development and tests.
   */
  simulate(input: {
    providerDeviceId: string;
    plateNumber: string;
    direction: TravelDirection;
    confidence?: number;
    capturedAt?: Date;
    vehicleClassHint?: VehicleClass | null;
  }): NormalizedAnprEvent {
    this.sequence += 1;
    const capturedAt = input.capturedAt ?? new Date();

    return {
      // Deterministic and unique, so replaying the same simulated arrival is
      // caught by the same idempotency rule a real duplicate would hit.
      providerEventId: `mock-${capturedAt.getTime()}-${this.sequence}`,
      providerDeviceId: input.providerDeviceId,
      capturedAt,
      plateNumberRaw: input.plateNumber,
      confidence: input.confidence ?? 0.96,
      direction: input.direction,
      vehicleClassHint: input.vehicleClassHint ?? null,
      imageBase64: null,
      plateImageBase64: null,
      raw: {
        simulator: true,
        notice: 'Generated by MockAnprProvider. Not a real camera capture.',
        sequence: this.sequence,
      },
    };
  }
}
