import { Inject, Injectable } from '@nestjs/common';
import { createHash } from 'node:crypto';

import { FuelType, HypothecationStatus, VehicleClass } from '@smartpark/contracts';
import { APP_CONFIG, AppConfig } from '@/config/configuration';
import {
  RegistryLookupResult,
  RegistryProviderError,
  VehicleRegistryProvider,
  VehicleRegistryRecord,
} from '../vehicle-registry.provider';

/**
 * Development simulator for the vehicle registry.
 *
 * This exists because the authorised VAHAN access route is unresolved
 * (docs/open-items.md OI-01) and development cannot wait for it. It is a
 * SIMULATOR, and it never pretends otherwise:
 *
 *   - `source` is 'MOCK' on every record, which is persisted and displayed.
 *   - `authoritative` is false, so the vehicle service records the enrichment
 *     as UNAVAILABLE rather than VAHAN_VERIFIED. A mock-sourced vehicle is
 *     never shown as registry-verified anywhere in the platform.
 *   - The configuration guard refuses to start production with this provider.
 *
 * Behaviour is DETERMINISTIC: output is derived from a hash of the plate, so
 * the same registration always yields the same owner, financier and model.
 * Tests can assert on it, and a demo behaves the same way twice.
 *
 * It also simulates the failure modes that matter, so the retry, circuit
 * breaker and manual-review paths are exercised in development rather than
 * discovered in production:
 *   ~4% of plates are "not found", and ~3% raise a transient error.
 *
 * All names and addresses are obviously fictional (requirement S45: never use
 * real people's personal information).
 */
@Injectable()
export class MockVehicleRegistryProvider extends VehicleRegistryProvider {
  readonly name = 'mock';
  readonly configured = true;
  readonly authoritative = false;

  constructor(@Inject(APP_CONFIG) private readonly config: AppConfig) {
    super();
  }

  async lookup(normalizedRegistrationNumber: string): Promise<RegistryLookupResult> {
    const started = Date.now();
    const seed = hashToInt(normalizedRegistrationNumber);

    // A realistic latency band, so timeout handling and the gate's
    // non-blocking design are genuinely exercised locally.
    await delay(120 + (seed % 380));

    const roll = seed % 100;

    if (roll < 3) {
      throw new RegistryProviderError(
        'UPSTREAM_UNAVAILABLE',
        'Simulated upstream failure from the registry simulator.',
        true,
        503,
      );
    }

    if (roll < 7) {
      return {
        outcome: 'NOT_FOUND',
        record: null,
        latencyMs: Date.now() - started,
        httpStatus: 404,
      };
    }

    return {
      outcome: 'FOUND',
      record: this.buildRecord(normalizedRegistrationNumber, seed),
      latencyMs: Date.now() - started,
      httpStatus: 200,
    };
  }

  private buildRecord(registrationNumber: string, seed: number): VehicleRegistryRecord {
    const vehicleClass = pick(VEHICLE_CLASSES, seed, 1);
    const modelEntry = pick(MODELS[vehicleClass] ?? MODELS.CAR!, seed, 2);
    const hypothecated = seed % 10 < 8;
    const financierName = hypothecated ? pick(FINANCIER_NAMES, seed, 3) : null;

    const registrationYear = 2015 + (seed % 10);

    return {
      registrationNumber,
      vehicleClass,
      vehicleType: modelEntry.bodyType,
      make: modelEntry.make,
      model: modelEntry.model,
      variant: pick(VARIANTS, seed, 4),
      color: pick(COLOURS, seed, 5),
      fuelType: pick(FUEL_TYPES, seed, 6),
      manufacturingYear: registrationYear,
      registeredOwnerName: buildOwnerName(seed),
      registeredOwnerAddress: buildOwnerAddress(seed),
      financierName,
      hypothecationStatus: hypothecated
        ? HypothecationStatus.HYPOTHECATED
        : HypothecationStatus.NOT_HYPOTHECATED,
      registrationDate: new Date(Date.UTC(registrationYear, seed % 12, (seed % 27) + 1)),
      fitnessValidUpto: new Date(Date.UTC(registrationYear + 15, seed % 12, (seed % 27) + 1)),
      insuranceValidUpto: new Date(Date.UTC(2026, seed % 12, (seed % 27) + 1)),
      chassisNumberLast4: String(1000 + (seed % 9000)),
      engineNumberLast4: String(1000 + ((seed * 7) % 9000)),
      source: 'MOCK',
      retrievedAt: new Date(),
      raw: {
        simulator: true,
        notice:
          'Generated by MockVehicleRegistryProvider. NOT authoritative registry data. ' +
          'The authorised VAHAN/aggregator route is open item OI-01.',
        seed,
        providerLatencyBudgetMs: this.config.registry.timeoutMs,
      },
    };
  }
}

/* ------------------------------------------------------------------ */
/* Deterministic fixture data - all fictional                          */
/* ------------------------------------------------------------------ */

const VEHICLE_CLASSES: VehicleClass[] = [
  VehicleClass.CAR,
  VehicleClass.CAR,
  VehicleClass.SUV,
  VehicleClass.TWO_WHEELER,
  VehicleClass.TWO_WHEELER,
  VehicleClass.LCV,
  VehicleClass.THREE_WHEELER,
  VehicleClass.HCV,
];

interface ModelEntry {
  make: string;
  model: string;
  bodyType: string;
}

/**
 * Vehicle makes and models are real products, not personal data, and using
 * plausible ones keeps the demo legible. Owners and financiers are invented.
 */
const MODELS: Partial<Record<VehicleClass, ModelEntry[]>> = {
  CAR: [
    { make: 'Maruti Suzuki', model: 'Swift', bodyType: 'Hatchback' },
    { make: 'Hyundai', model: 'i20', bodyType: 'Hatchback' },
    { make: 'Tata', model: 'Tiago', bodyType: 'Hatchback' },
    { make: 'Honda', model: 'City', bodyType: 'Saloon' },
    { make: 'Maruti Suzuki', model: 'Dzire', bodyType: 'Saloon' },
  ],
  SUV: [
    { make: 'Mahindra', model: 'Scorpio', bodyType: 'SUV' },
    { make: 'Tata', model: 'Nexon', bodyType: 'Compact SUV' },
    { make: 'Hyundai', model: 'Creta', bodyType: 'SUV' },
    { make: 'Kia', model: 'Seltos', bodyType: 'SUV' },
  ],
  TWO_WHEELER: [
    { make: 'Hero', model: 'Splendor Plus', bodyType: 'Motorcycle' },
    { make: 'Honda', model: 'Activa', bodyType: 'Scooter' },
    { make: 'Bajaj', model: 'Pulsar 150', bodyType: 'Motorcycle' },
    { make: 'TVS', model: 'Jupiter', bodyType: 'Scooter' },
  ],
  THREE_WHEELER: [
    { make: 'Bajaj', model: 'RE Compact', bodyType: 'Auto rickshaw' },
    { make: 'Piaggio', model: 'Ape Xtra', bodyType: 'Goods carrier' },
  ],
  LCV: [
    { make: 'Tata', model: 'Ace Gold', bodyType: 'Light goods vehicle' },
    { make: 'Mahindra', model: 'Bolero Pik-Up', bodyType: 'Light goods vehicle' },
  ],
  HCV: [
    { make: 'Tata', model: 'LPT 1613', bodyType: 'Heavy goods vehicle' },
    { make: 'Ashok Leyland', model: 'Ecomet 1215', bodyType: 'Heavy goods vehicle' },
  ],
};

/**
 * Invented lender names.
 *
 * Deliberately NOT real financial institutions: seeded demo data must not imply
 * a commercial relationship Sri JP does not have. The seed creates matching
 * financier master records so alias resolution has something to resolve to.
 */
const FINANCIER_NAMES = [
  'Northbridge Vehicle Finance Limited',
  'Sundara Capital Finance Ltd',
  'Meridian Auto Loans Pvt Ltd',
  'Kaveri Commercial Credit Ltd',
  'Everest Retail Finance Limited',
  'Palmgrove Asset Finance Pvt Ltd',
];

const VARIANTS = ['LXI', 'VXI', 'ZXI', 'Base', 'Sportz', 'Asta', 'XM', 'XZ Plus'];
const COLOURS = ['White', 'Silver', 'Grey', 'Blue', 'Red', 'Black', 'Beige'];
const FUEL_TYPES: FuelType[] = [
  FuelType.PETROL,
  FuelType.DIESEL,
  FuelType.PETROL,
  FuelType.CNG,
  FuelType.ELECTRIC,
];

const GIVEN_NAMES = [
  'Arun', 'Bhavna', 'Chetan', 'Divya', 'Farid', 'Gita', 'Harish', 'Ishita',
  'Jaya', 'Kiran', 'Lalitha', 'Manoj', 'Nithya', 'Omkar', 'Preeti', 'Rakesh',
];
const FAMILY_NAMES = [
  'Ramanathan', 'Deshpande', 'Iyer', 'Sharma', 'Fernandes', 'Reddy',
  'Chatterjee', 'Nair', 'Patel', 'Kulkarni',
];
const STREETS = [
  'Anna Salai', 'MG Road', 'Nehru Street', 'Gandhi Nagar Main Road',
  'Lake View Avenue', 'Temple Street',
];
const CITIES = [
  'Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Tiruchirappalli', 'Bengaluru',
];

function buildOwnerName(seed: number): string {
  return `${pick(GIVEN_NAMES, seed, 7)} ${pick(FAMILY_NAMES, seed, 8)}`;
}

function buildOwnerAddress(seed: number): string {
  const doorNumber = (seed % 180) + 1;
  return `${doorNumber}, ${pick(STREETS, seed, 9)}, ${pick(CITIES, seed, 10)}, Tamil Nadu`;
}

/** Stable 31-bit integer from the plate, so output never varies run to run. */
function hashToInt(value: string): number {
  const digest = createHash('sha256').update(value).digest();
  return digest.readUInt32BE(0) % 2_147_483_647;
}

function pick<T>(items: readonly T[], seed: number, salt: number): T {
  return items[(seed * salt) % items.length] as T;
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
