/**
 * The single catalogue of machine-readable error codes returned by the API.
 *
 * Contract with clients:
 *   - `code` is stable and safe to branch on.
 *   - `message` is human-readable and may change; never parse it.
 *   - `details` is an optional, code-specific object. It never contains
 *     stack traces, SQL, credentials or upstream payloads.
 *
 * Every code maps to exactly one HTTP status via `ERROR_STATUS`.
 */
export const ErrorCode = {
  /* --- Generic -------------------------------------------------- */
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',

  /* --- Authentication / authorisation --------------------------- */
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  MFA_REQUIRED: 'MFA_REQUIRED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SITE_ACCESS_DENIED: 'SITE_ACCESS_DENIED',
  FINANCIER_SCOPE_VIOLATION: 'FINANCIER_SCOPE_VIOLATION',
  PASSWORD_POLICY_VIOLATION: 'PASSWORD_POLICY_VIOLATION',

  /* --- Concurrency / idempotency -------------------------------- */
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD:
    'IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',

  /* --- Site / topology ------------------------------------------ */
  SITE_NOT_ACTIVE: 'SITE_NOT_ACTIVE',
  SITE_MODE_MISMATCH: 'SITE_MODE_MISMATCH',
  GATE_NOT_AT_SITE: 'GATE_NOT_AT_SITE',
  LANE_DIRECTION_MISMATCH: 'LANE_DIRECTION_MISMATCH',
  ZONE_CAPACITY_EXCEEDED: 'ZONE_CAPACITY_EXCEEDED',
  PARKING_SPACE_NOT_AVAILABLE: 'PARKING_SPACE_NOT_AVAILABLE',
  NO_SPACE_AVAILABLE: 'NO_SPACE_AVAILABLE',

  /* --- Vehicle -------------------------------------------------- */
  INVALID_REGISTRATION_NUMBER: 'INVALID_REGISTRATION_NUMBER',
  VEHICLE_ALREADY_ACTIVE: 'VEHICLE_ALREADY_ACTIVE',
  VEHICLE_NOT_ON_SITE: 'VEHICLE_NOT_ON_SITE',
  INVALID_VEHICLE_STATE_TRANSITION: 'INVALID_VEHICLE_STATE_TRANSITION',

  /* --- ANPR ----------------------------------------------------- */
  ANPR_DEVICE_UNKNOWN: 'ANPR_DEVICE_UNKNOWN',
  ANPR_DEVICE_DISABLED: 'ANPR_DEVICE_DISABLED',
  ANPR_SIGNATURE_INVALID: 'ANPR_SIGNATURE_INVALID',
  ANPR_EVENT_DUPLICATE: 'ANPR_EVENT_DUPLICATE',
  ANPR_CONFIDENCE_TOO_LOW: 'ANPR_CONFIDENCE_TOO_LOW',
  ANPR_EVENT_ALREADY_RESOLVED: 'ANPR_EVENT_ALREADY_RESOLVED',
  MANUAL_OVERRIDE_NOT_PERMITTED: 'MANUAL_OVERRIDE_NOT_PERMITTED',

  /* --- Vehicle registry (VAHAN / aggregator) -------------------- */
  REGISTRY_PROVIDER_NOT_CONFIGURED: 'REGISTRY_PROVIDER_NOT_CONFIGURED',
  REGISTRY_LOOKUP_FAILED: 'REGISTRY_LOOKUP_FAILED',
  REGISTRY_CIRCUIT_OPEN: 'REGISTRY_CIRCUIT_OPEN',
  REGISTRY_RECORD_NOT_FOUND: 'REGISTRY_RECORD_NOT_FOUND',

  /* --- Financier / contract / rating ---------------------------- */
  FINANCIER_INACTIVE: 'FINANCIER_INACTIVE',
  FINANCIER_NOT_MATCHED: 'FINANCIER_NOT_MATCHED',
  NO_ACTIVE_CONTRACT: 'NO_ACTIVE_CONTRACT',
  CONTRACT_VERSION_NOT_EDITABLE: 'CONTRACT_VERSION_NOT_EDITABLE',
  CONTRACT_PERIOD_OVERLAP: 'CONTRACT_PERIOD_OVERLAP',
  NO_APPLICABLE_RATE_PLAN: 'NO_APPLICABLE_RATE_PLAN',
  RATE_PLAN_INVALID: 'RATE_PLAN_INVALID',
  RATE_SLABS_NOT_CONTIGUOUS: 'RATE_SLABS_NOT_CONTIGUOUS',
  RATE_SLABS_OVERLAP: 'RATE_SLABS_OVERLAP',
  RATE_PLAN_NOT_EDITABLE: 'RATE_PLAN_NOT_EDITABLE',

  /* --- Parking session / charges -------------------------------- */
  SESSION_NOT_OPEN: 'SESSION_NOT_OPEN',
  SESSION_ALREADY_CLOSED: 'SESSION_ALREADY_CLOSED',
  INVALID_SESSION_STATE_TRANSITION: 'INVALID_SESSION_STATE_TRANSITION',
  EXIT_BEFORE_ENTRY: 'EXIT_BEFORE_ENTRY',
  CHARGE_CALCULATION_STALE: 'CHARGE_CALCULATION_STALE',

  /* --- Billing / invoice / payment ------------------------------ */
  BILLING_PARTY_UNRESOLVED: 'BILLING_PARTY_UNRESOLVED',
  BILLING_PARTY_DETAILS_MISSING: 'BILLING_PARTY_DETAILS_MISSING',
  INVOICE_ALREADY_EXISTS: 'INVOICE_ALREADY_EXISTS',
  INVALID_INVOICE_STATE_TRANSITION: 'INVALID_INVOICE_STATE_TRANSITION',
  INVOICE_NOT_PAYABLE: 'INVOICE_NOT_PAYABLE',
  INVOICE_PDF_NOT_AVAILABLE: 'INVOICE_PDF_NOT_AVAILABLE',
  PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_BALANCE',
  INVALID_PAYMENT_STATE_TRANSITION: 'INVALID_PAYMENT_STATE_TRANSITION',
  PAYMENT_PROVIDER_NOT_CONFIGURED: 'PAYMENT_PROVIDER_NOT_CONFIGURED',
  PAYMENT_WEBHOOK_SIGNATURE_INVALID: 'PAYMENT_WEBHOOK_SIGNATURE_INVALID',
  TAX_PROFILE_NOT_CONFIGURED: 'TAX_PROFILE_NOT_CONFIGURED',
  INVOICE_SERIES_NOT_CONFIGURED: 'INVOICE_SERIES_NOT_CONFIGURED',

  /* --- Release -------------------------------------------------- */
  RELEASE_NOT_ELIGIBLE: 'RELEASE_NOT_ELIGIBLE',
  RELEASE_ALREADY_REQUESTED: 'RELEASE_ALREADY_REQUESTED',
  RELEASE_NOT_APPROVED: 'RELEASE_NOT_APPROVED',
  RELEASE_ALREADY_COMPLETED: 'RELEASE_ALREADY_COMPLETED',
  INVALID_RELEASE_STATE_TRANSITION: 'INVALID_RELEASE_STATE_TRANSITION',
  SELF_APPROVAL_NOT_PERMITTED: 'SELF_APPROVAL_NOT_PERMITTED',
  OUTSTANDING_BALANCE_BLOCKS_RELEASE: 'OUTSTANDING_BALANCE_BLOCKS_RELEASE',
  RELEASE_AUTHORIZATION_INVALID: 'RELEASE_AUTHORIZATION_INVALID',

  /* --- Auction -------------------------------------------------- */
  INVALID_AUCTION_STATE_TRANSITION: 'INVALID_AUCTION_STATE_TRANSITION',
  INVALID_LOT_STATE_TRANSITION: 'INVALID_LOT_STATE_TRANSITION',
  AUCTION_NOT_OPEN: 'AUCTION_NOT_OPEN',
  AUCTION_WINDOW_CLOSED: 'AUCTION_WINDOW_CLOSED',
  VEHICLE_NOT_AUCTION_ELIGIBLE: 'VEHICLE_NOT_AUCTION_ELIGIBLE',
  VEHICLE_ALREADY_IN_AUCTION: 'VEHICLE_ALREADY_IN_AUCTION',
  BIDDER_NOT_APPROVED: 'BIDDER_NOT_APPROVED',
  BIDDER_NOT_REGISTERED_FOR_AUCTION: 'BIDDER_NOT_REGISTERED_FOR_AUCTION',
  BID_BELOW_RESERVE: 'BID_BELOW_RESERVE',
  BID_BELOW_MINIMUM_INCREMENT: 'BID_BELOW_MINIMUM_INCREMENT',
  BID_NOT_HIGHEST: 'BID_NOT_HIGHEST',
  BID_IMMUTABLE: 'BID_IMMUTABLE',
  WINNER_ALREADY_SELECTED: 'WINNER_ALREADY_SELECTED',
  NO_ELIGIBLE_BIDS: 'NO_ELIGIBLE_BIDS',
  SETTLEMENT_ALREADY_EXISTS: 'SETTLEMENT_ALREADY_EXISTS',
  SETTLEMENT_NOT_COMPLETE: 'SETTLEMENT_NOT_COMPLETE',

  /* --- Notification / document ---------------------------------- */
  NOTIFICATION_TEMPLATE_NOT_FOUND: 'NOTIFICATION_TEMPLATE_NOT_FOUND',
  NOTIFICATION_TEMPLATE_RENDER_FAILED: 'NOTIFICATION_TEMPLATE_RENDER_FAILED',
  NOTIFICATION_PROVIDER_NOT_CONFIGURED: 'NOTIFICATION_PROVIDER_NOT_CONFIGURED',
  NO_RECIPIENT_CONFIGURED: 'NO_RECIPIENT_CONFIGURED',
  DOCUMENT_NOT_AVAILABLE: 'DOCUMENT_NOT_AVAILABLE',
  DOCUMENT_REJECTED_BY_SCAN: 'DOCUMENT_REJECTED_BY_SCAN',
  OBJECT_STORAGE_UNAVAILABLE: 'OBJECT_STORAGE_UNAVAILABLE',

  /* --- Configuration -------------------------------------------- */
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',
  SETTING_TYPE_MISMATCH: 'SETTING_TYPE_MISMATCH',
  CONFIGURATION_REQUIRED: 'CONFIGURATION_REQUIRED',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** HTTP status for every error code. Keep exhaustive. */
export const ERROR_STATUS: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  RATE_LIMITED: 429,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,

  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  REFRESH_TOKEN_REUSED: 401,
  ACCOUNT_LOCKED: 423,
  ACCOUNT_NOT_ACTIVE: 403,
  MFA_REQUIRED: 401,
  PERMISSION_DENIED: 403,
  SITE_ACCESS_DENIED: 403,
  FINANCIER_SCOPE_VIOLATION: 403,
  PASSWORD_POLICY_VIOLATION: 400,

  CONCURRENT_MODIFICATION: 409,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD: 409,
  REQUEST_IN_PROGRESS: 409,

  SITE_NOT_ACTIVE: 409,
  SITE_MODE_MISMATCH: 409,
  GATE_NOT_AT_SITE: 400,
  LANE_DIRECTION_MISMATCH: 400,
  ZONE_CAPACITY_EXCEEDED: 409,
  PARKING_SPACE_NOT_AVAILABLE: 409,
  NO_SPACE_AVAILABLE: 409,

  INVALID_REGISTRATION_NUMBER: 400,
  VEHICLE_ALREADY_ACTIVE: 409,
  VEHICLE_NOT_ON_SITE: 409,
  INVALID_VEHICLE_STATE_TRANSITION: 409,

  ANPR_DEVICE_UNKNOWN: 404,
  ANPR_DEVICE_DISABLED: 403,
  ANPR_SIGNATURE_INVALID: 401,
  ANPR_EVENT_DUPLICATE: 409,
  ANPR_CONFIDENCE_TOO_LOW: 422,
  ANPR_EVENT_ALREADY_RESOLVED: 409,
  MANUAL_OVERRIDE_NOT_PERMITTED: 403,

  REGISTRY_PROVIDER_NOT_CONFIGURED: 503,
  REGISTRY_LOOKUP_FAILED: 502,
  REGISTRY_CIRCUIT_OPEN: 503,
  REGISTRY_RECORD_NOT_FOUND: 404,

  FINANCIER_INACTIVE: 409,
  FINANCIER_NOT_MATCHED: 409,
  NO_ACTIVE_CONTRACT: 409,
  CONTRACT_VERSION_NOT_EDITABLE: 409,
  CONTRACT_PERIOD_OVERLAP: 409,
  NO_APPLICABLE_RATE_PLAN: 409,
  RATE_PLAN_INVALID: 400,
  RATE_SLABS_NOT_CONTIGUOUS: 400,
  RATE_SLABS_OVERLAP: 400,
  RATE_PLAN_NOT_EDITABLE: 409,

  SESSION_NOT_OPEN: 409,
  SESSION_ALREADY_CLOSED: 409,
  INVALID_SESSION_STATE_TRANSITION: 409,
  EXIT_BEFORE_ENTRY: 400,
  CHARGE_CALCULATION_STALE: 409,

  BILLING_PARTY_UNRESOLVED: 409,
  BILLING_PARTY_DETAILS_MISSING: 400,
  INVOICE_ALREADY_EXISTS: 409,
  INVALID_INVOICE_STATE_TRANSITION: 409,
  INVOICE_NOT_PAYABLE: 409,
  INVOICE_PDF_NOT_AVAILABLE: 404,
  PAYMENT_EXCEEDS_BALANCE: 400,
  INVALID_PAYMENT_STATE_TRANSITION: 409,
  PAYMENT_PROVIDER_NOT_CONFIGURED: 503,
  PAYMENT_WEBHOOK_SIGNATURE_INVALID: 401,
  TAX_PROFILE_NOT_CONFIGURED: 409,
  INVOICE_SERIES_NOT_CONFIGURED: 409,

  RELEASE_NOT_ELIGIBLE: 409,
  RELEASE_ALREADY_REQUESTED: 409,
  RELEASE_NOT_APPROVED: 409,
  RELEASE_ALREADY_COMPLETED: 409,
  INVALID_RELEASE_STATE_TRANSITION: 409,
  SELF_APPROVAL_NOT_PERMITTED: 403,
  OUTSTANDING_BALANCE_BLOCKS_RELEASE: 409,
  RELEASE_AUTHORIZATION_INVALID: 400,

  INVALID_AUCTION_STATE_TRANSITION: 409,
  INVALID_LOT_STATE_TRANSITION: 409,
  AUCTION_NOT_OPEN: 409,
  AUCTION_WINDOW_CLOSED: 409,
  VEHICLE_NOT_AUCTION_ELIGIBLE: 409,
  VEHICLE_ALREADY_IN_AUCTION: 409,
  BIDDER_NOT_APPROVED: 403,
  BIDDER_NOT_REGISTERED_FOR_AUCTION: 403,
  BID_BELOW_RESERVE: 422,
  BID_BELOW_MINIMUM_INCREMENT: 422,
  BID_NOT_HIGHEST: 422,
  BID_IMMUTABLE: 409,
  WINNER_ALREADY_SELECTED: 409,
  NO_ELIGIBLE_BIDS: 409,
  SETTLEMENT_ALREADY_EXISTS: 409,
  SETTLEMENT_NOT_COMPLETE: 409,

  NOTIFICATION_TEMPLATE_NOT_FOUND: 404,
  NOTIFICATION_TEMPLATE_RENDER_FAILED: 500,
  NOTIFICATION_PROVIDER_NOT_CONFIGURED: 503,
  NO_RECIPIENT_CONFIGURED: 409,
  DOCUMENT_NOT_AVAILABLE: 404,
  DOCUMENT_REJECTED_BY_SCAN: 422,
  OBJECT_STORAGE_UNAVAILABLE: 503,

  SETTING_NOT_FOUND: 404,
  SETTING_TYPE_MISMATCH: 400,
  CONFIGURATION_REQUIRED: 409,
};

/** The exact JSON body shape returned for every non-2xx response. */
export interface ApiErrorBody {
  code: ErrorCode | string;
  message: string;
  correlationId: string;
  timestamp: string;
  path?: string;
  details?: Record<string, unknown>;
}

export function httpStatusForErrorCode(code: string): number {
  return ERROR_STATUS[code as ErrorCode] ?? 500;
}
